drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    website_url  TEXT NOT NULL,
    website_description TEXT NOT NULL
);

insert into bookmarks (title, website_url, website_description)
values
	('Google', 'https://www.google.com', 'this is a search engine'),
	('Amazon', 'https://www.amazon.com', 'this is a ecommerce store'),
	('Twitch', 'https://www.twitch.tv', 'this is a live streaming video platform'),
	('YouTube', 'https://www.youtube.com', 'this is a video sharing website'),
	('Wikipedia', 'https://www.wikipedia.org', 'this is a multilingual online encyclopedia'),
	('Gmail', 'https://www.gmail.com', 'this is a free email service developed by Google'),
	('LinkedIn', 'https://www.linkedin.com', 'this is a online business and employment-oriented service'),
	('Stack Overflow', 'https://stackoverflow.com', 'this is a a question and answer site for professional and enthusiast programmers'),
	('Facebook', 'https://www.facebook.com', 'this is a online social media and social networking service company'),
	('Netflix', 'https://www.netflix.com', 'this is a online media-services provider and production company');
